name: Build and Test
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build-gcc:
    runs-on: ubuntu-latest
    container:
      image: gcc:16
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y cmake catch2 libboost-dev
      - name: Configure CMake
        run: >
          cmake -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DCMAKE_CXX_STANDARD=23
          -S .
      - name: Build
        run: cmake --build build --config Release
      - name: Run Tests
        working-directory: build
        run: ctest --build-config Release --output-on-failure
      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-gcc-16
          path: build

  build-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-clang20
          restore-keys: |
            ${{ runner.os }}-apt-
      - name: Install Clang 20
        run: |
          sudo apt-get update
          sudo apt-get install -y wget software-properties-common lsb-release gnupg
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          clang-20 --version
          clang++-20 --version
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y catch2 libboost-dev
      - name: Configure CMake
        run: >
          cmake -B build -DCMAKE_CXX_COMPILER=clang++-20 -DCMAKE_C_COMPILER=clang-20 -DCMAKE_BUILD_TYPE=Release -DTESTS=ON
          -DCMAKE_CXX_STANDARD=23 -S .
      - name: Build
        run: cmake --build build --config Release
      - name: Run Tests
        working-directory: build
        run: ctest --build-config Release --output-on-failure
      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-clang-20
          path: build
